#Definir pod
apiVersion: apps/v1
kind: deployment
metadata:
  name: msreniec
  labels:
    app: msreniec
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: msreniec
        template:
        metadata:
        labels:
          app: msreniec
          spec:
          containers:
          name: msreniec
          image: 123

          resources:
          requests:
          memory: "256Mi"
          cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
    imagePullSecrets:
      name: regcred
      ##################
    kind :  Service
    apiVersion: v1   
    metadata:
      name: msreniec
    spec:
      selector:
        app: msreniec
      ports:
      - port: 80
        targetPort: <Target Port>
    
